# Generated by Django 4.1.3 on 2022-11-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
            options={
                'verbose_name': 'Competence',
                'verbose_name_plural': 'Competences',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Sphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
            options={
                'verbose_name': 'Sphere',
                'verbose_name_plural': 'Spheres',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='consultant',
            name='competences',
            field=models.ManyToManyField(to='consultants.competence'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='spheres',
            field=models.ManyToManyField(to='consultants.sphere'),
        ),
    ]
