# Generated by Django 4.1.3 on 2022-11-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_competence_sphere_consultant_competences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='consultant',
            name='competence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='tasks_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='languages',
            field=models.ManyToManyField(to='consultants.language'),
        ),
    ]
