# Generated by Django 4.1.3 on 2022-11-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0004_type_consultant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='daily_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
