# Generated by Django 4.1.3 on 2022-11-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0005_consultant_age_consultant_daily_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
