# Generated by Django 4.1.3 on 2022-11-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0006_consultant_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
