# Generated by Django 4.1.3 on 2022-11-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0007_consultant_email_consultant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
