# Generated by Django 4.1.3 on 2022-12-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0008_consultant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
